### ISSUE TITLE
kafka-oauth-client supported for use with Quarkus (native)?

### ISSUE THREAD

**Issue by merlante** [strimzi/strimzi-kafka-oauth#122]
Hi, I have a question as to whether kafka-oauth-client should support Quarkus kafka (native) use cases. I ran into the issue, below, but I'm not sure whether it lives with you guys or with the Quarkus guide.

I am using kafka-oauth-client to support OAuth for Kafka in Quarkus (as described in [Quarkus - Using Apache Kafka with Reactive Messaging guide](https://quarkus.io/guides/kafka)). As in #105, I am using JaasClientOauthLoginCallbackHandler in a config like
```
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=OAUTHBEARER
kafka.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.client.id="${CLIENT_ID}" \
  oauth.client.secret="${CLIENT_SECRET}" \
  oauth.token.endpoint.uri="${TOKEN_ENDPOINT_URI}" ;
kafka.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
```
in my quarkus app and when I do a **native build** with a dependency for strimzi-kafka-oauth versions >=0.8.0 I get an exception:
```
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.nimbusds.jose.Payload.toJSONObject(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing io.strimzi.kafka.oauth.common.NimbusPayloadTransformer.transform(NimbusPayloadTransformer.java:15)
Call path from entry point to io.strimzi.kafka.oauth.common.NimbusPayloadTransformer.transform(Payload): 
        at io.strimzi.kafka.oauth.common.NimbusPayloadTransformer.transform(NimbusPayloadTransformer.java:15)
        at io.strimzi.kafka.oauth.common.NimbusPayloadTransformer.transform(NimbusPayloadTransformer.java:11)
        at com.nimbusds.jose.Payload.toType(Payload.java:495)
        at io.strimzi.kafka.oauth.common.TokenIntrospection.introspectAccessToken(TokenIntrospection.java:31)
        at io.strimzi.kafka.oauth.common.OAuthAuthenticator.loginWithAccessToken(OAuthAuthenticator.java:35)
        at io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.handleCallback(JaasClientOauthLoginCallbackHandler.java:157)
        at com.oracle.svm.reflect.JaasClientOauthLoginCallbackHandler_handleCallback_dc35cf084af502a75da6c142d5c6a98a97f92099_455.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at io.undertow.websockets.annotated.BoundMethod.invoke(BoundMethod.java:87)
        at io.undertow.websockets.annotated.AnnotatedEndpoint$3.run(AnnotatedEndpoint.java:156)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
...
```
I'm guessing this issue was introduced in the move from keycloak auth to nimbus  (see [Release notes 0.8.0](https://github.com/strimzi/strimzi-kafka-oauth/releases/tag/0.8.0)).

Anyway, I'm not necessarily saying that you guys should have to fix this "issue". Given that strimzi-kafka-oauth is a generic library, and not a supported quarkus extension or library, but is cited for use in a Quarkus guide, I was wondering if you guys have an opinion on,
a) Should strimzi-kafka-client be supported and tested for use with Quarkus (including native)?
OR
b) Should the Quarkus guide(s) reference a different library that they then test and support themselves?

If a) is the case, then the above turns out to be a bug, but if b) is the case, it's the guides that need amending and some new lib which is explicitly test against native app builds needs to be found. I'm happy to raise this issue with the Quarkus folks if you guys think it lives with them.

Thanks!

**Comment by scholzj** [comment]
Shouldn't they have some working version of the OAuth library fixed in the Quarkus BOM and have it tested against the docs? Or should they specify the version in the guide? Or did you manually override the OAuth version to 0.8.x?

I think it is Quarkus decision what libraries they want to support and test with. We are happy if the choose Strimzi OAuth library and can try to help where needed. But IMHO the integration needs to sit with Quarkus so that it can be part of their release cycle, tests etc. They are also the ones who understand the details of the things such as native builds etc. 

Anything what sits in the Strimzi repo will be always just catching up with a released Quarkus versions. But we also do not have the capacity to directly support all the different frameworks which might be interested in integrating the OAuth library.

**Comment by mstruk** [comment]
We use [nimbus-jose-jwt 9.10](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/df2c40bb5ce0c9f8af96c6cd2f7b81d8cecf1707/src/main/java/com/nimbusds/jose/Payload.java#lines-340) which apparently contains this method that we're using.

We updated the nimbus-jose-jwt version between 0.8.0 and 0.8.1 release so make sure to use the latter.

Or maybe could it be that some other dependency in your code transitively pulls in an older nimbus-jose-jwt and overrides the one expected by strimzi-kafka-oauth?

**Comment by merlante** [comment]
Thanks guys. FWIW, the guide does not specify a version, but 0.7.2 works, and 0.8.0 and 0.8.1 do not work. (Maybe the stack trace was from when I checked 0.8.0.)

Anyway, I think @scholzj has addressed the main point. Something has to happen on the Quarkus side so that a working version of the library (or some other library) is referenced in guides and/or set in the quarkus bom.

**Comment by mstruk** [comment]
See https://github.com/quarkusio/quarkus/issues/18398#issuecomment-921712179 for how to fix the issue with native build.
