### ISSUE TITLE
kafka 3.0

### ISSUE THREAD

**Issue by emaciejm** [strimzi/strimzi-kafka-oauth#128]
Have you checked the compatibility with Kafka 3.0? In my opinion, it does not work.

**Comment by scholzj** [comment]
On which side? Client or server?

**Comment by emaciejm** [comment]
The broker does not start after adding strimzi oauth libraries. I'm not 100% sure, but here could be the reason: 
https://issues.apache.org/jira/browse/KAFKA-12590

**Comment by scholzj** [comment]
So is it just the authorization? What version of the OAuth library are you using? The authentication is IMHO covered in our system tests. I think the authroization should be as well.

**Comment by emaciejm** [comment]
I used version 0.8.1 ( turned on: strimzi.authorization.delegate.to.kafka.acl=true)
error:
ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.NoClassDefFoundError: kafka/security/auth/SimpleAclAuthorizer

**Comment by scholzj** [comment]
Yeah, looks like we need to update some things. We will have a look at it, thanks for reporting it. The STs do not seem to cover the delegation :-/.

**Comment by emaciejm** [comment]
Díky moc.

**Comment by scholzj** [comment]
Should be fixed in [0.9.0-rc1](https://github.com/strimzi/strimzi-kafka-oauth/releases/tag/0.9.0-rc1) ... please give it a try if you want.

**Comment by scholzj** [comment]
Closing as the 0.9.0 is now release.

**Comment by emaciejm** [comment]
Hey, I would like to ask if strimzi's authentication and authorization also
works with Kafka running without a zookeeper.  and what to pay attention to
when migrating Kafka to kraft, in the context of strimzi-auth.  Thank you
in advance for your answer.
 Regards.
Maciej Malecki

**Comment by mstruk** [comment]
I'm starting to add tests for Kraft mode.

AFAICT the authentication part works.
For Keycloak authorization there has been an issue opened #178. That will have to be fixed.
