### ISSUE TITLE
Error with Running with Keycloak using SSL

### ISSUE THREAD

**Issue by namson0482** [strimzi/strimzi-kafka-oauth#160]
Running with Keycloak using SSL: It can't build docker with Keycloak SSL. 

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/2830607/193380055-0086d8f4-cd6f-43de-a606-e0f5c3bd5f99.png">

**Comment by scholzj** [comment]
Sharing the full log instead of a screenshot and explaining what exactly are you doing might be a good start.

**Comment by namson0482** [comment]
Below, what I am doing:

Step 1: Open folder trimzi-kafka-oauth/examples/docker

Step 2: docker-compose -f compose.yml -f kafka-oauth-strimzi/compose-ssl.yml -f keycloak/compose-ssl.yml -f keycloak-import/compose-ssl.yml up --build

Final, I get errors such as above

Notes: My computer is Macbook (intel chip).

**Comment by scholzj** [comment]
@namson0482 Please share the full log as well.
@mstruk Any idea?

**Comment by mstruk** [comment]
This looks like an issue introduced when keycloak image in the examples was updated to version 19.0.1-legacy.

There is no test in CI for making sure docker-compose builds in the examples work. Something we should look into.

**Comment by namson0482** [comment]
@scholzj 
@mstruk 
Full log as below

![Uploading image.png…]()

**Comment by mstruk** [comment]
This should be fixed by #161.

@namson0482 Thanks for reporting this.
