### ISSUE TITLE
It has a new issue with keycloak without SSL

### ISSUE THREAD

**Issue by namson0482** [strimzi/strimzi-kafka-oauth#166]
Hi,

It can't build up docker container keycloak without SSL successfully. What I see in console. It tell  me keycloak can't connect to database. Please review images below:
![1](https://user-images.githubusercontent.com/2830607/195248231-e03ff24b-200d-48bc-9c18-b00312748597.png)
![2](https://user-images.githubusercontent.com/2830607/195248922-274f41ea-845c-4a72-b8e0-862638ebb542.png)

[keycloak_console.zip](https://github.com/strimzi/strimzi-kafka-oauth/files/9761460/keycloak_console.zip)

Please open zip file to see log fully. How to re-produce my error

Step 1: Go to folder strimzi-kafka-oauth/examples/docker

Step 2: Execute the command: docker-compose -f compose.yml -f keycloak/compose.yml up

I get errors like above.  I guess root cause because we change keycloak from keycloak:19.0.1-legacy to keycloak:19.0.2-legacy in this ticket https://github.com/strimzi/strimzi-kafka-oauth/commit/181719341087fc774d02abfdd7d5aa9fa12d059e 

Thanks

**Comment by mstruk** [comment]
I can't reproduce your issue. Works fine for me. The latest main uses keycloak:19.0.2-legacy.

**Comment by namson0482** [comment]
@mstruk 
I already checked with a other Macbook then it can run as well. We can closed this ticket.
Thanks so much for your message
