### ISSUE TITLE
Class JaasServerOauthValidatorCallback could not be found

### ISSUE THREAD

**Issue by mroiter-larus** [strimzi/strimzi-kafka-oauth#246]
Hi! 

i'm trying to setup SASL/OAUTHBEARER on my Kafka instance installed as Docker container. I've deployed your JARs into my Kafka container, by mounting a volume to a subdirectory of the "/usr/share/java/kafka" directory, which is the default Kafka libs directory. 
Kafka container starts correctly, but as soon as i define the environment variables for the OAUTH listeners, such as:

```
KAFKA_LISTENER_NAME_SASL__SSL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
```

after restarting the container i'll get the following error during the startup:

```
kafka  | [2024-09-09 17:37:39,100] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka  | org.apache.kafka.common.config.ConfigException: Invalid value io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler for configuration sasl.server.callback.handler.class: Class io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler could not be found.
kafka  | 	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
kafka  | 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
kafka  | 	at org.apache.kafka.common.config.AbstractConfig.valuesWithPrefixOverride(AbstractConfig.java:316)
kafka  | 	at kafka.server.KafkaConfig.valuesWithPrefixOverride(KafkaConfig.scala:1563)
kafka  | 	at kafka.server.KafkaConfig.saslEnabledMechanisms(KafkaConfig.scala:1912)
kafka  | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2305)
kafka  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2107)
kafka  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1534)
kafka  | 	at kafka.Kafka$.buildServer(Kafka.scala:73)
kafka  | 	at kafka.Kafka$.main(Kafka.scala:93)
kafka  | 	at kafka.Kafka.main(Kafka.scala)
```

It seems the strimzi-kafka-oauth JARs are not loaded successfully in the classpath. Do you have any suggestion on how to correctly install them?

Thanks in advance for your help!

**Comment by scholzj** [comment]
You probably placed them on the wrong path? Or you are missing some JARs? Hard to say with the information you provided.

**Comment by mroiter-larus** [comment]
@scholzj thanks for your reply! I've solved building my own image and COPYing the JARs inside the container.
