### ISSUE TITLE
Can not get token from server

### ISSUE THREAD

**Issue by msilvestre** [strimzi/strimzi-kafka-oauth#35]
Hi! I'm trying to use strimizi in order to authenticate clients with kafka using a JWT given from a keycloak server.

It is unable to token to server giving me error 400 INVALID_CREDENTIALS: Invalid client credentials.

I could manage to fix this changing the following code on oauth-common/src/main/java/io/strimzi/kafka/oauth/common/OAuthAuthenticator.java:loginWithClientSecret [56]:

```java
 public static TokenInfo loginWithClientSecret(URI tokenEndpointUrl, SSLSocketFactory socketFactory,
                                                  HostnameVerifier hostnameVerifier,
                                                  String clientId, String clientSecret, boolean isJWT) throws IOException {
        if (log.isDebugEnabled()) {
            log.debug("loginWithClientSecret() - tokenEndpointUrl: {}, clientId: {}, clientSecret: {}",
                    tokenEndpointUrl, clientId, mask(clientSecret));
        }

       // Start of code change
        String authorization = null; //"Basic " + base64encode(clientId + ':' + clientSecret);

        StringBuilder body = new StringBuilder("grant_type=password&client_id=curl&username="+clientId+"&password="+clientSecret);
      // End of code change
        return post(tokenEndpointUrl, socketFactory, hostnameVerifier, authorization, body.toString(), isJWT);
    }
```

This is the way my server gives me the token. Can you guys support this? or should I make a PR? If so can you please give me some light on how to make this? Like should we pass a new environment variable in order to build this kind of body?

Thank you.

**Comment by mstruk** [comment]
It looks like you're are using username and password, rather than clientId and secret. You should configure a new client in your Keycloak realm and set it to confidential rather than public. Also enable service account on it. You should then be able to make it work without your 'hack'. What you did here is just use a regular username and password, but clientId can't be set to username - it has to be set to actual clientId. Alternatively, if you wanted to use username and password you have to obtain a refresh token or access token and set that instead of clientId and secret.

**Comment by msilvestre** [comment]
Hi! Thank you for your fast reply.

Just tried with the clientId and secret and all went well.

Also:
In order to get thins moving I used a different kafka.server configuration:

```bash
# Enable OAUTHBEARER as SASL mechanism
sasl.enabled.mechanisms=OAUTHBEARER
# Configure a listener for client applications
listeners=SASL_PLAINTEXT://localhost:9092
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=OAUTHBEARER

listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
listener.name.sasl_plaintext.oauthbearer.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
listener.name.sasl_plaintext.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
```
