### ISSUE TITLE
Use refresh token received from the server if the token differs from the configured one

### ISSUE THREAD

**Issue by danny2394** [strimzi/strimzi-kafka-oauth#43]
I am configuring the Kafka Broker with a refresh token which it successfully uses to get a access token from Keycloak.

I wanted to set up a max times a refresh token can be used in Keycloak however Kafka only uses the refresh token that is configured via the environment variable.
This is can also be the case where the refresh token has some max lifespan after which one would have to change the refresh token and restart the Kafka node.
Is something like this possible currently?

**Comment by mstruk** [comment]
Can you share you server.properties so I can get a better idea of what you are trying to achieve?

Refresh token on Kafka Broker could only be used for broker acting as a Kafka client for inter-broker communication, which you can more robustly achieve by using mutual TLS over an additional listener.

**Comment by danny2394** [comment]
I am using the refresh tokens by configuring the Kafka broker to act as a client for inter-broker communication.
In Keycloak, refresh tokens come with an expiration time and additionally can be configured to be used only a certain number of times. Either way, the refresh token that is configured on the Kafka broker will be invalid either by using it or certain times or because it's expired (as Keycloak expires it, I haven't found a way to have a non-expiring refresh token on Keycloak).

I am using Kafka in a docker container, so I am configuring it via environment variables, and I have attached a snippet of those to give you an idea what I am doing, also there are some variables filled by Ansible during deployment.



      # Must be included 
      KAFKA_ADVERTISED_HOST_NAME: "{{ kafka_advertised_hostname }}"

      # Port configuration for communication
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://{{ kafka_advertised_hostname }}:9092"

      # SASL authentication determined by run mode, should typically be SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SASL_SSL"

      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;"
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler

      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

      # Internal KAFKA rules
      # Specify the inter broker listener - this is usually not the same as for external clients, but in this example it is
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      # Specify OAUTHBEARER to be used as inter broker SASL protocol
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_LOG4J_ROOT_LOGLEVEL: "{{ kafka_log_level }}"
      KAFKA_TOOLS_LOG4J_LOGLEVEL: "{{ kafka_log_level }}"

      # Zookeeper server necessary to support Kafka
      KAFKA_ZOOKEEPER_CONNECT: "{{ zookeeper_container_name }}:2181"

      KAFKA_SSL_KEYSTORE_LOCATION: "/kafka.keystore.jks"

      KAFKA_SSL_KEYSTORE_PASSWORD: "{{ kafka_ssl_keystore_password }}"
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      # Specify OAuth2 Token Endpoint URL to your authorization server
      # For production you should always use https url - see examples/docker/kafka-oauth-strimzi/compose-ssl.yml
      OAUTH_TOKEN_ENDPOINT_URI: "REDACTED"
      # Specify valid Issuer URI
      # Only access tokens issued by this issuer will be accepted
      OAUTH_VALID_ISSUER_URI: "REDACTED"
      # Specify configured client id of Kafka broker - same for all brokers.
      # You have to manually register this client with your authorization server
      # (you may use a different client id and secret accordingly).
      OAUTH_CLIENT_ID: REDACTED
      # Specify configured secret for Kafka broker - same for all brokers
      OAUTH_CLIENT_SECRET: "REDACTED"
      OAUTH_INTROSPECTION_ENDPOINT_URI: "REDACTED"
      OAUTH_REFRESH_TOKEN: "REDACTED"

      ## KIP 386 so clients are forced to reauthenticate every hour
      KAFKA_CONNECTIONS_MAX_REAUTH_MS: "3600000"

I am suggesting If we could set up an initial Refresh token to use on startup and eventually before it expires or the access token expires, refresh it which will also provide a new refresh token.

Another strategy that could be used is if the client on Keycloak is configured for Service accounts,
and since the configuration already has a clientID and clientSecret, it could be used to receive an access token.


The mutual TLS suggestion makes sense and is more robust, however in a research organization for prototyping purposes I do not think I can use that right now due to extra maintenance of self-signed certificates.

**Comment by mstruk** [comment]
Take a look at [Authorization Tutorial](examples/README-authz.md#power-user-can-do-anything) where it demonstrates how to obtain from Keycloak a so called `offline token` which is a refresh token that never expires.
