### ISSUE TITLE
TLS SNI connection to keycloak

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-oauth#86]
Is the TLS connection made to keycloak by default use SNI? 

https://www.cloudflare.com/learning/ssl/what-is-sni/
https://en.wikipedia.org/wiki/Server_Name_Indication

We are trying to ensure that we install the correct certificate in the trust store. The cert may be different depending on SNI vs non-SNI.

**Comment by scholzj** [comment]
@mstruk Do you have an idea?

**Comment by mstruk** [comment]
We use java.net.HttpsURLConnection which fully supports SNI, so as long as the truststores are configured with proper certificates it should work.

**Comment by jrivers96** [comment]
This worked properly. We were configuring a WAF.
