### ISSUE TITLE
 Enable strimzi-kafka-oauth on ppc64le arch 

### ISSUE THREAD

**Issue by krishvoor** [strimzi/strimzi-kafka-oauth#94]
Hey!

Thanks for the awesome readme/tutorials on strimzi-kafka-oauth. I could build strimzi-kafka-oauth from source & run the tests outlined, I was wondering what it would take to have the strimzi-kafka-oauth running on ppc64le. FWIW we have ppc64le instances in Travis.

**Comment by scholzj** [comment]
The OAuth libraries are just Java ... why do they need some special release for ppc64le?

**Comment by krishvoor** [comment]
Please accept my apologies, working across different Strimzi-* repo(s) - I got myself lost, I will push a PR soon for your review.
